### ISSUE TITLE
Flash Loans for Starknet

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/backlog#4]
# Description

Implement Flash Loans for Starknet, based on ERC-7399.

# Resources

- [ERC7399 reference implementation](https://github.com/alcueca/erc7399-reference)
- [EIP-7399 Pull Request](https://github.com/ethereum/EIPs/pull/7400)

**Comment by rahulghangas** [comment]
@abdelhamidbakhta https://github.com/aerius-labs/cairo-flash-loan

**Comment by abdelhamidbakhta** [comment]
> https://github.com/aerius-labs/cairo-flash-loan
Oh very cool!
Will close this one then
